baseURL = "https://ge2019.nti.me.uk/"
languageCode = "en-gb"
title = "General Election 2019"
theme = "mediumish-gohugo-theme"
copyright = "2019. All rights reserved."

[permalinks]
  tactical = "/:section/:filename/"
  tools = "/:filename/"

[taxonomies]
  goal = "goals"
  tacticalgoal = "tacticalgoals"
  tacticalmethod = "tacticalmethods"

[params]
  logo = "/images/logo.png"
  description = ""
  tacticaldetails = false

[params.author]
  name = "James Taylor"
  thumbnail = "/images/tbc.png"
  description = "TBC"

[params.index]
#  picture = "/images/tbc.jpg"
  title = "General Election 2019"
  subtitle = ""
  alertbar = true

[params.social]
  github = "jt-nti/ge2019"
  twitter = "jtonline"

## Main Menu
[[menu.main]]
  name = "Tactical Voting Tools"
  weight = 100
  identifier = "tactical"
  url = "/tactical/"

[[menu.main]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/about/"
